import type { Metadata } from 'next';
import './globals.css';
import { QueryProvider } from '@/contexts/QueryProvider';
import ClientHeader from '@/components/common/Header';

export const metadata: Metadata = {
  title: 'epigram',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ClientHeader />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
